### ISSUE TITLE
[Discussion] Should Migrate drop tables that are not part of your schema?

### ISSUE THREAD

**Issue by jonaswide** [prisma/migrate#163]
As of now you can alter and drop data and tables in your database by changing or removing model definitions in the generated `schema.prisma` file.

I'm not sure that I'm confident with the possibility of accidentally dropping full tables by removing the type model from the schema. 

Say that I have some tables that I don't want to expose to the api. I would actually end up deleting the table and the data after generating the prisma2 schema if I were to remove the types and then running `prisma2 dev`. 

**If** it indeed is expected and purposed behaviour, we should at least perhaps discuss some security matters here. 
Even though I believe that I'd be more confident using prisma2 knowing that this couldn't actually happen (again haha). Maybe lift should just cross reference the database for the defined models without altering the whole database?

**Comment by janpio** [comment]
You refer to a "generated `schema.prisma` file". What exactly do you mean by that?

In general, "alter and drop data and tables in your database by changing or removing model definitions in the [...] schema.prisma file" is exactly what Lift does.

But you raise 2 very valid points:

1. 

> accidentally dropping full tables by removing the type model from the schema

We are currently working on making destructive changes as a result of schema changes more explicit by giving the user a warning both when creating the migration in the first place (`lift save`) and also again when applying it (`lift up`). (We do not 100% know how to handle that in `prisma2 dev` where these steps are executed automatically, but will come up with something.)

2.

> Say that I have some tables that I don't want to expose to the api. I would actually end up deleting the table and the data after generating the prisma2 schema if I were to remove the types and then running `prisma2 dev`.

This is another interesting thing: Right now I don't think we have a way to not handle that. I think this issue here should be mainly about this, so we can discuss the reasoning and possible solutions for this.

**Comment by janpio** [comment]
(I updated the title of the issue to reflect, that I think it would be best to focus on your second point.)

**Comment by albertoperdomo** [comment]
Will be addressed via https://github.com/prisma/migrate/issues/613
