### ISSUE TITLE
[Question] Unclear how breaking changes detection is working.

### ISSUE THREAD

**Issue by sameoldmadness** [prisma/migrate#204]
Seems like neither `DROP COLUMN` nor `DROP TABLE` causes a breaking change dialog.

What's the heuristic for this?

**Comment by sameoldmadness** [comment]
```
Checking the datasource for potential data loss...

Database Changes:

Migration                         Database actions         Status

20191029113029-update  1 DropTable statements.  Done 🚀

You can get the detailed db changes with prisma2 lift up --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md

SQL Commands:

-- Start Migrations

-- Migration 20191029113029-checkout-labeling
DROP TABLE "public"."Payload";
ALTER TABLE "public"."Payload" DROP COLUMN "merchant";
```

**Comment by tomhoule** [comment]
Our current logic is to check for the presence of data in the table or the column. For a table, if there is at least 1 row, the warning should be triggered, and for columns we count the non-null values. We will warn if there is any data in the table/column that is about to be dropped, and not warn otherwise.

I hope this answers the question :)
