### ISSUE TITLE
SQLite create DB fails

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#299]
Again, with preview 19

Once I fix the schema from https://github.com/prisma/prisma2/issues/1294

Running lift up fails, 

1. I can see an `undefined` in the name

![image](https://user-images.githubusercontent.com/746482/71996459-893b1a80-323c-11ea-9bf9-f420ff80800c.png)

2. Gets stuck here with no error

![image](https://user-images.githubusercontent.com/746482/71996485-96f0a000-323c-11ea-8d86-5e014349f2bb.png)

**Comment by divyenduz** [comment]
Related issue: https://github.com/prisma/specs/issues/385

**Comment by pantharshit00** [comment]
This issue was happening when we had the old schema init flow and you would select `Just the schema` option. It would bootstrap the schema with the `sqlite://` protocol which is not supported.

Instead, we support `sqlite:`(note no `//`) now which is like an alias of `file:`. So I am going to close this issue now as this problem doesn't exist now.

**Comment by janpio** [comment]
> It would bootstrap the schema with the sqlite:// protocol which is not supported.
> Instead, we support sqlite:(note no //) now which is like an alias of file:.

Is this just a bug or really the wanted behavior? I am not sure that this is actually correct.

**Comment by pantharshit00** [comment]
The bug was that we were generating `sqlite://` which resolved to root `/`. Since init flow was removed it got automatically fixed.

**Comment by janpio** [comment]
So if someone was using `sqlite://` manually they would still have the same problem?

**Comment by pantharshit00** [comment]
Yes, but right now the protocol is `sqlite:` without `//` this is expected
