### ISSUE TITLE
how to run lift to alter table without data loss ?

### ISSUE THREAD

**Issue by justicejoe** [prisma/migrate#326]
I change only this in Schema
![image](https://user-images.githubusercontent.com/16795429/73065488-3c12a600-3ed6-11ea-9b0a-8b5668b03d1a.png)

![image](https://user-images.githubusercontent.com/16795429/73065656-acb9c280-3ed6-11ea-8974-772b58fc1a04.png)

but all the data in that table are loss.  It said that i alter every column but I just add property to one column.

how to migrate table without data loss ?

sometime I just add a properties to the column , and sometime add new column, but then all the data in that table are gone.

**Comment by pantharshit00** [comment]
@justicejoe Can you tell me which connector you are using?

We fixed a similar bug in the past few days so can you please try again with the latest alpha(`npm install -g prisma2@alpha`) and report back.

**Comment by justicejoe** [comment]
@pantharshit00 I use postgresql as database

**Comment by pantharshit00** [comment]
Ok, you are changing a non unique value to a unique one. To migrate without any data loss here, you will need to ensure that all of the rows in your database has a unique column value for this field. Can you please make sure you have that?

Otherwise, we can't migrate it without data loss as that would violate the null constraint.

**Comment by Jolg42** [comment]
https://github.com/prisma/migrate/issues/471

**Comment by tomhoule** [comment]
Closing this because this has improved a lot in the migration engine. If you encounter specific problems, please open a new issue. Thank you!
