### ISSUE TITLE
Wrong name in error message

### ISSUE THREAD

**Issue by scriptcoded** [prisma/migrate#333]
Hey,

Prisma Migrate gave me this error
```
 ERROR  Oops, an unexpected error occured!
Error in migration engine.
Reason: [src/libcore/result.rs:1165:5] Error parsing the migration steps: Error("missing field `tag`", 
line: 1, column: 46)

Please create an issue in the lift repo with
your `schema.prisma` and the prisma2 command you tried to use 🙏:
https://github.com/prisma/lift/issues/new
```

Notice then line `Please create an issue in the lift repo with`. I'm guessing you'd like it to say something like `Please create an issue in the Migrate repo`.

The funny thing is that the correct message is in the code https://github.com/prisma/migrate/blob/de0006c99b2a56381073f672a37ca83ed7032d2b/src/LiftEngine.ts#L296

Prisma 2 version: `prisma2@2.0.0-preview020.3, binary version: 45dd3493ff2fd09b5a8cdf697de276e368f7ebee`

**Comment by pantharshit00** [comment]
It is also left in many other places as mentioned by one of our user in this comment: https://github.com/prisma/prisma2/issues/1476#issuecomment-580121750

**Comment by Jolg42** [comment]
Thank you @scriptcoded for the report! 👍 

Indeed I renamed that almost at the same time than for the latest preview release but it wasn't included in it.

But this issue was a great reminder as I found more renaming to do 😇 fixed with https://github.com/prisma/migrate/commit/73cfa50b6aa6133aa9eb61ae9b78f625dc593a86
