### ISSUE TITLE
`--delete-db` on migrate down

### ISSUE THREAD

**Issue by Errorname** [prisma/migrate#350]
For my use-case (multi-tenancy), I often need to be able to create and delete database for the tenants.

There already is a `--create-db` option on migrate up to create a database, but I think it would be helpful to also have a `--delete-db` option on migrate down instead of having to manually delete the database.

**Comment by albertoperdomo** [comment]
Thanks for taking the time to suggest this improvement! @Errorname 

Prisma Migrate Preview ([released 2.13.0](https://github.com/prisma/prisma/releases/tag/2.13.0)) has a `prisma migrate reset` command you can use for this purpose. I hope this works for you.

Since this issue is from the experimental version of Prisma Migrate, I am going to ahead and close it. If `prisma migrate reset` does not suit your needs please open a new issue [here](https://github.com/prisma/prisma/issues/new/choose).
