### ISSUE TITLE
`README.md` of migration folder includes `quaint` in SQL

### ISSUE THREAD

**Issue by janpio** [prisma/migrate#354]
```
## Database Steps

´´´sql
CREATE TABLE "quaint"."locations" (
    "id" TEXT NOT NULL  ,
    "latitude" REAL NOT NULL DEFAULT 0 ,
    "longitude" REAL NOT NULL DEFAULT 0 ,
    PRIMARY KEY ("id")
) 
´´´
```

**Comment by pantharshit00** [comment]
This is specific to sqlite.

**Comment by tomhoule** [comment]
I remember an issue with a discussion about this a few months ago. The conclusion is that it's harmless and it would be non-trivial amounts of work to remove. On the other hand we could change the `"quaint"` thing to something else very easily, since it's just the name the database is bound to on that sqlite connection.

**Comment by janpio** [comment]
Does this have to be present or could we just replace it with nothing?

**Comment by tomhoule** [comment]
Replacing with nothing is significant work but not impossible. Changing the name of the binding is easy.

**Comment by janpio** [comment]
Well, before printing it to a file we could just replace the string `"quaint".` with and empty string ` `. Not _that_ much work :)

**Comment by tomhoule** [comment]
yep, it's not universal but it kind of works indeed.
