### ISSUE TITLE
Unable to migrate required relationship fields

### ISSUE THREAD

**Issue by seanemmer** [prisma/migrate#379]
I am consolidating two related bug reports I have created that have gone unresolved.  These bugs can be reproduced using the prisma-examples/typescript/script example by running the following command:
`prisma2 migrate save --experimental && prisma2 migrate up --experimental`

**1) Unable to add a required field**

Error:  
```
ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error q
uerying the database: Null constraint failed: (foobar))
```

Reproduction Steps:
Remove `post.Author` field.  Run migration.  Add post.foobar field of type `User`.  Run migration.

Original Report: (12/6/2019)
https://github.com/prisma/migrate/issues/236

**2) Unable to convert from optional to required field**

Error: 
```
ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error q
uerying the database: Null constraint failed: (author))
```

Reproduction steps:
Update `post.Author` type from `User` to `User?`

Original Report: (12/6/2019):
https://github.com/prisma/migrate/issues/240

**Comment by seanemmer** [comment]
Confirming that this issue is still occurring in the Prisma Beta.  

This bug has been floating around since December (https://github.com/prisma/migrate/issues/240).

**Comment by pantharshit00** [comment]
> 1) Unable to add a required field

This issue is confirmed. Basically the problem here is database can't fill cuids when apply that change as the database doesn't know what a cuid is.

> 2) Unable to convert from optional to required field

This is resolved now in `beta.2`. You will get a proper validation error.
![image](https://user-images.githubusercontent.com/22195362/80088323-fb303900-8579-11ea-9a3f-04333af56b28.png)


So I am going to close this issue. Please follow https://github.com/prisma/migrate/issues/236 for the remaining cuid issue.
