### ISSUE TITLE
Recommend deleting migrations folder as temporary workaround

### ISSUE THREAD

**Issue by schickling** [prisma/migrate#389]
## Problem

With migrations currently still being experimental it's unfortunately possible to end up in situation where a user is "stuck" and runs into errors like these:

- https://github.com/prisma/migrate/issues/385
- https://github.com/prisma/migrate/issues/382
- https://github.com/prisma/migrate/issues/383

In many of these situations it helps to delete the `migrations` folder and to re-create + re-run the migrations as a workaround.

## Solution

Until we've solved all of these problems, I suggest we add a helpful note to the printed error message that describes this workaround.

**Comment by tomhoule** [comment]
very much a detail, but for the sake of completeness: users should delete the migrations folder and the _Migration table in their database

**Comment by janpio** [comment]
Do we have a way to reliably identify these cases @tomhoule?

**Comment by tomhoule** [comment]
They're in several, well identified places so yes.

**Comment by tvvignesh** [comment]
Have been getting these errors on my end as well and have been following the workaround. Its quite complicated on my end though since I am working with Microservices architecture with migrations done via CI/CD.

Have to delete migrate folder from every microservice, delete _Migration table from all databases in local, dev and prod environments (3x work), generate new migrations for every service and run CI/CD again for all environments to apply the migrations.

Wish migrate would come out of preview soon :crossed_fingers: 

The other trouble I am facing is upgrading package versions, breaking changes in every microservice. Things are hard when you are working with microservices :sob:
