### ISSUE TITLE
Error with npx prisma migrate up --experiemental

### ISSUE THREAD

**Issue by JCLMAQ** [prisma/migrate#403]
Error report: 
report id 2640

**Comment by pantharshit00** [comment]
@JCLMAQ Sorry for the late reply here. 

I checked the error report. Your datamodel has various issues like missing directives. Please upgrade to `beta.2` to get proper validation about these errors and run `prisma validate`.

I am not sure if it will be okay to put your datamodel in public so that is why I am not specifically discussing the errors. Please try fixing it yourself once using the validation errors.

**Comment by JCLMAQ** [comment]
Hi, I get through the error working on the schema and with beta.2 version.
For now, it's running without eror.
By the way, the datamodel is just a test schema nothing which could not be public.
Still get a question, where is the doc for "prisma validate" command ?
Thanks.

**Comment by pantharshit00** [comment]
"prisma validate" is something that is not meant to be used in the normal workflow so that is why it is not documented. Use "prisma generate" instead.

We use `validate` internally in the CI, I guess shouldn't have mentioned it 😅
