### ISSUE TITLE
Flag to error and exit when there is potential data loss

### ISSUE THREAD

**Issue by markrieth** [prisma/migrate#557]
## Problem
First I want to prevent a "fat finger" mistake in the CLI that results in data loss. 
Second, I want to automatically run migrations as a part of deployment. I also want to ensure that my automatic migrations aren't resulting in any data loss. The deployment should fail if there will be any potential data loss for the migration. In other words, the answer to "There will be data loss, do you want to continue?" is always ***No***.  In that case I will address the data issue and attempt deployment again. Think of it like a failing test / build failure. 

## Suggested solution
There should be a flag to _automatically exit with an error status & message_ when there is potential data loss.

**Comment by tomhoule** [comment]
Thanks for taking the time to request this feature!

We've recently released a Prisma Migrate Preview ([2.1.3.0 release notes](https://github.com/prisma/prisma/releases/tag/2.13.0)), which has quite a few changes compared to the previous experimental version. We believe this issue is no longer relevant in this new version, so we are closing this. More specifically, you will not get any interactive behaviour in `prisma migrate deploy --preview`. The warnings are in the file, and you can decide to push that migration towards your production deployment or not.

We would encourage you to try out Prisma Migrate Preview. If you come across this or any other issue in the preview version, please feel free to open a [new issue in prisma/prisma](https://github.com/prisma/prisma/issues/new/choose).
For general feedback on Prisma Migrate Preview, feel free to chime in [on this issue](https://github.com/prisma/prisma/issues/4531).
