### ISSUE TITLE
Prisma Migrate crashed. 

### ISSUE THREAD

**Issue by himalayaahuja** [prisma/migrate#615]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v12.17.0           | 
| Prisma CLI  | 2.9.0              | 
| Binary      | 369b3694b7edb869fad14827a33ad3f3f49bbc20| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:98:76] called `Result::unwrap()` on an `Err` value: ConnectorError { user_facing_error: None, kind: QueryError(Null constraint failed: (revision)), context: SpanTrace [{ target: "migration_core::api", name: "ApplyMigration", fields: "migration_id=\"20200925070840\"", file: "migration-engine/core/src/api.rs", line: 93 }] }

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```

**Comment by tomhoule** [comment]
Thanks for taking the time to report this issue!

We've recently released a Prisma Migrate Preview ([2.1.3.0 release notes](https://github.com/prisma/prisma/releases/tag/2.13.0)), which has quite a few changes compared to the previous experimental version. We believe this issue is no longer relevant in this new version, so we are closing this.

We would encourage you to try out Prisma Migrate Preview. If you come across this or any other issue in the preview version, please feel free to open a [new issue in prisma/prisma](https://github.com/prisma/prisma/issues/new/choose).
For general feedback on Prisma Migrate Preview, feel free to chime in [on this issue](https://github.com/prisma/prisma/issues/4531).
