### ISSUE TITLE
Crash error using Prisma Migrate

### ISSUE THREAD

**Issue by namlxuit056** [prisma/migrate#665]
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v12.18.4           | 
| Prisma CLI  | 2.13.0-integration-runtime-browser-build.4| 
| Binary      | 91fe309fbdac0a7ee646b93830bb9a80ed6a04bd| 

## Error
```
Error: [libs/datamodel/connectors/dml/src/model.rs:164:14] We assume an internally valid datamodel before mutating.
```

**Comment by albertoperdomo** [comment]
@namlxuit056 Can you please confirm which version of `@prisma/cli` you are using?
Can you please make sure to use `@prisma/cli` 2.13.0 and see if you can reproduce?


`2.13.0-integration-runtime-browser-build.4` seems to be an integration version we user for integration internally we don't support publicly. If it's an error with the version output we can look into that, but in order to consider this an issue it needs to be happening in an official release.

**Comment by namlxuit056** [comment]
File schema prisma exist model, when  i can't Migrate, but when i remove all model in file, it work with me. Old version 2.10 not crash like that.
