### ISSUE TITLE
Postgres tables are quoted when created

### ISSUE THREAD

**Issue by matthewmueller** [prisma/migrate#69]
Based on: https://prisma.slack.com/archives/CKQTGR6T0/p1563892709024100

<img width="484" alt="Screen Shot 2019-07-24 at 10 20 57 AM" src="https://user-images.githubusercontent.com/170299/61777155-c0d41880-adfc-11e9-80fb-00954b987eaf.png">

I can confirm that with:

```sql
CREATE TABLE "public"."Post"("id" text NOT NULL  ,"createdAt" timestamp(3) NOT NULL  ,"updatedAt" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,"published" boolean NOT NULL DEFAULT false ,"title" text NOT NULL DEFAULT '' ,"content" text   ,PRIMARY KEY ("id"));
```

You can *only* select the table via `select * from "Post"`. 
This doesn't work: `select * from Post`.

We need to be smarter about what tables need quotes and what tables do not.

**Comment by mikeslade** [comment]
@matthewmueller this behavior is found in the fields on the tables as well.

`CREATE TABLE "public"."Agent"("id" text NOT NULL  ,"firstName" text NOT NULL DEFAULT '' ,"middleName" text   ,"lastName" text NOT NULL DEFAULT '' ,"suffix" text   ,"recordStatus" text NOT NULL DEFAULT 'ACTIVE' ,"createdAt" timestamp(3) NOT NULL  ,"updatedAt" timestamp(3) NOT NULL DEFAULT '1970-01-01 00:00:00' ,PRIMARY KEY ("id"));`

None of these are reserved words in Postgres, but result in table creation like depicted below:

![image](https://user-images.githubusercontent.com/573965/61897564-ecc6cb00-aedc-11e9-86ae-be1e4b5fff10.png)
 
Which then requires queries like this to fetch items:

`SELECT "firstName", "lastName", suffix FROM "Agent"`

Looking further, it seems that Postgres just forces everything to lowercase if it is not surrounded by quotes. Given that the docs recommend PascalCase for models and camelCase for field names, I understand why the team simply wrapped everything in quotes. It is the only way to preserve the case-sensitive formatting in the table names and the field names. This does create some inconsistency for field names without capital letters, since Postgres drops the quotes on its own in that scenario.

**Comment by matthewmueller** [comment]
Leaving this here as well for reference: https://lerner.co.il/2013/11/30/quoting-postgresql/

**Comment by matthewmueller** [comment]
It turns out postgres is a bit weird and if we want capitalized models (to match the schema), we'll need to use double quotes. It looks like ActiveRecord also does it this way.

Would a possible solution be to lowercase everything? It would mean that `BlogTag` would become `blogtag` in the database but that may be ok.
